version: "3.9"
services:
    app:
        build:
            context: ./
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/src/app
    nginx:
        build:
            context: ./docker/nginx
        ports:
            - "8080:80"