version: "3.9"
services:
    app:
        build:
            context: ./
            dockerfile: docker/php/Dockerfile

    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./public:/src/app/public