version: "3.9"
services:
    app:
        build:
            context: ./
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/src/app

    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./public:/src/app/public
        ports:
            - "8080:80"
